In [1]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))


True
0
1
NVIDIA GeForce RTX 3070


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [14]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5
inputs

[tensor([[-0.8996,  0.5313,  0.4034]]),
 tensor([[ 1.4521, -2.4182, -1.1906]]),
 tensor([[0.6964, 1.1296, 0.2214]]),
 tensor([[-0.0558,  1.2057,  1.9486]]),
 tensor([[-0.0766, -0.8562, -0.7870]])]

In [4]:
# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))

hidden

(tensor([[[ 0.5438, -0.4057,  1.1341]]]),
 tensor([[[-1.1115,  0.3501, -0.7703]]]))

In [12]:
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    view = i.view(1, 1, -1)
    print(view)
    print("-"*20)
    out, hidden = lstm(view, hidden)
    print(out)
    print("-"*20)
    print(hidden)
    print("="*30)

tensor([[[ 0.5119, -0.6368,  1.0429]]])
--------------------
tensor([[[ 0.1990, -0.0406, -0.1692]]], grad_fn=<StackBackward0>)
--------------------
(tensor([[[ 0.1990, -0.0406, -0.1692]]], grad_fn=<StackBackward0>), tensor([[[ 0.5052, -0.2285, -0.4953]]], grad_fn=<StackBackward0>))
tensor([[[ 0.4903,  1.0318, -0.5989]]])
--------------------
tensor([[[ 0.1939, -0.0463,  0.0238]]], grad_fn=<StackBackward0>)
--------------------
(tensor([[[ 0.1939, -0.0463,  0.0238]]], grad_fn=<StackBackward0>), tensor([[[ 0.3800, -0.1626,  0.0492]]], grad_fn=<StackBackward0>))
tensor([[[ 1.6015, -1.0735, -1.2173]]])
--------------------
tensor([[[-0.1052, -0.1215,  0.5482]]], grad_fn=<StackBackward0>)
--------------------
(tensor([[[-0.1052, -0.1215,  0.5482]]], grad_fn=<StackBackward0>), tensor([[[-0.1496, -0.5206,  0.7594]]], grad_fn=<StackBackward0>))
tensor([[[ 0.6472, -0.0412, -0.1775]]])
--------------------
tensor([[[-0.0193, -0.0928,  0.3600]]], grad_fn=<StackBackward0>)
--------------------
(te

In [16]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state

In [17]:
print(inputs)
print(hidden)

tensor([[[ 1.5980, -1.1685,  0.7591]],

        [[-1.8689,  0.5573,  0.1582]],

        [[-0.9813, -0.8757, -0.2630]],

        [[ 0.0085,  0.0678, -0.2043]],

        [[-0.5243, -0.3088,  0.4444]]])
(tensor([[[-0.9864, -1.8248,  0.5989]]]), tensor([[[1.1414, 0.0319, 0.3748]]]))


In [18]:
out, hidden = lstm(inputs, hidden)
print(out)
print(hidden)

tensor([[[-0.0183,  0.0531,  0.2621]],

        [[ 0.0085,  0.1370, -0.1178]],

        [[-0.0510,  0.0022, -0.1677]],

        [[-0.0770, -0.1074, -0.1255]],

        [[-0.0685, -0.0587, -0.1290]]], grad_fn=<StackBackward0>)
(tensor([[[-0.0685, -0.0587, -0.1290]]], grad_fn=<StackBackward0>), tensor([[[-0.2283, -0.1268, -0.2386]]], grad_fn=<StackBackward0>))
